### ISSUE TITLE
Link "libraries required by PHOEBE" does not work

### ISSUE THREAD

**Issue by majkelx** [phoebe-project/phoebe2-docs#15]
On the page http://www.phoebe-project.org/1.0/download, in the section **Download the Mac version**, link: [libraries required by PHOEBE](http://www.phoebe-project.org/?q=node/3) does not work.

**Comment by kecnry** [comment]
Thanks for pointing this out - we seem to have lost some legacy-related content when migrating everything to the new website.  Once we track down the missing content, I'll fix the broken link and close the issue.

**Comment by kecnry** [comment]
Sorry for the delay - we've updated the instructions for installing PHOEBE 1.0 legacy on Macs and hopefully included all required dependencies.  Please let us know if you run into any issues!

http://www.phoebe-project.org/1.0/download
