### ISSUE TITLE
issue with v2.2 docs: api/phoebe.parameters.dataset.lc

### ISSUE THREAD

**Issue by srmoon400** [phoebe-project/phoebe2-docs#20]
hi what do i set value for flux?

**Comment by kecnry** [comment]
You'll generally use this in a script as:
```
b = phoebe.default_binary()
b.add_dataset('lc', times=[...], fluxes=[...], dataset='lc01')
```
where you (optionally) pass your observation data as arrays to `times` and `fluxes`. After `add_dataset`, you can always set or change values of the added parameters with 
```
b.set_value('fluxes', dataset='lc01', value=[...])
```

The [tutorials](http://phoebe-project.org/docs/latest) are a good place to start, with the [dataset tutorial](http://phoebe-project.org/docs/latest/tutorials/datasets) explaining this topic in detail.

I'll close this issue for now, but feel free to reply back if you run into any issues (or email me directly), or let us know if you have any suggestions to clarify this in the documentation.

**Comment by srmoon400** [comment]
hi tnx very much

**Comment by srmoon400** [comment]
Hello
I have a few problems in phoebe with Python
1: How can I choose  model overcontact binary not in thermal contact?
2: How can I quantify sma  and pot?
I set all Instructions tutorials but i have attach image
can you help me ?

**Comment by kecnry** [comment]
[This tutorial](http://phoebe-project.org/docs/2.3/tutorials/requiv_crit_contact) covers the basics of contact systems.  Contact systems are not in thermal contact by default in phoebe 2 (you would need to constrain the temperatures to be the same otherwise).
