### ISSUE TITLE
issue with v2.3 docs: tutorials/LC_estimators

### ISSUE THREAD

**Issue by gamal-hamed** [phoebe-project/phoebe2-docs#21]
Lc_geometry is not recognizing ('diagnose') keyword and it raises the following error:

----------------------------------------------------------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-30-c2cfc835eb35> in <module>()
      1 %matplotlib qt
----> 2 b.run_solver('lcgeom', solution='lcgeom_solution',diagnose=True)

3 frames
/usr/local/lib/python3.7/dist-packages/phoebe/frontend/bundle.py in _kwargs_checks(self, kwargs, additional_allowed_keys, additional_forbidden_keys, warning_only, ps)
   2806                     logger.warning(msg)
   2807                 else:
-> 2808                     raise KeyError(msg)
   2809 
   2810             if isinstance(value, dict):

KeyError: "'diagnose' not a recognized kwarg"

**Comment by kecnry** [comment]
Thanks for pointing this out.  `diagnose` is not officially included in the released version of PHOEBE (although may be re-included in the future).  The tutorial on the website should be updated shortly with that fixed.
