### ISSUE TITLE
issue with v2.4 docs: tutorials/beaming_boosting

### ISSUE THREAD

**Issue by qintianp** [phoebe-project/phoebe2-docs#28]
Hi, sir.
Although the support for Doppler boosting has been dropped in PHOEBE 2.2, ellc include the effect of Doppler Boosting. So can we solve Doppler boosting using ellc in phoebe?

**Comment by kecnry** [comment]
Not currently - the alternate backends are aimed to map the features and parameters supported in phoebe onto the other codes for comparison or to use for quicker initial estimation, but do not necessarily include support for everything natively available in those codes that are not implemented in phoebe itself.

See the [backend comparison table](http://phoebe-project.org/docs/2.4/examples/compute_comparison_table) for more details.

**Comment by qintianp** [comment]
OK, thanks very much
