### ISSUE TITLE
issue with v2.4 docs: tutorials/passbands

### ISSUE THREAD

**Issue by srkennelly** [phoebe-project/phoebe2-docs#34]
When I try to run the wget http://phoebe-project.org/static/atms/ck2004.tgz command, the permissions are denied and when I navigate to the url on a browser it also doesn't work.

**Comment by kecnry** [comment]
Thanks for reporting this.  

@aprsa - is [static/ck2004.tar](http://phoebe-project.org/static/ck2004.tar) the correct file?  Can we either create a soft-link or update the tutorial across all versions?

**Comment by aprsa** [comment]
@srkennelly, @kecnry: thanks for reporting this; the link is fine, the recent storm shut down our server's mount point that hosts this tarball. I managed to remount it and the link should work again. I will close this for now but feel free to reopen if there are any lingering issues.
