### ISSUE TITLE
issue with v2.4 docs: examples/sun

### ISSUE THREAD

**Issue by DAyres31** [phoebe-project/phoebe2-docs#38]
I am starting to work with phoebe and after installing the package in an anaconda environment I am trying to follow along example code in the PHOEBE documentation to get a grips of the functionalities and what not. I have ran into the following issue consistently after several hours of trouble shooting. I cannot figure out what this error is and how to fix it. Sidenote, I'm using jupyter notebooks.

AttributeError                            Traceback (most recent call last)
Cell In[12], line 4
      1 get_ipython().system('set PYTHONWARNINGS="ignore::ImportWarning"')
----> 4 import phoebe
      5 from phoebe import u # units
      6 import numpy as np

File ~\AppData\Roaming\Python\Python311\site-packages\phoebe\__init__.py:378
    376 from .dependencies.distl import gaussian, gaussian_around, normal, boxcar, uniform, uniform_around, histogram_from_bins, histogram_from_data, mvgaussian, mvhistogram_from_data
    377 from .atmospheres.passbands import install_passband, uninstall_passband, uninstall_all_passbands, download_passband, list_passband_online_history, update_passband_available, update_passband, update_all_passbands, list_all_update_passbands_available, list_online_passbands, list_installed_passbands, list_passbands, list_passband_directories, get_passband
--> 378 from .parameters import hierarchy, component, compute, constraint, dataset, feature, figure, solver, server
    379 from .frontend.bundle import Bundle
    380 from .backend import backends as _backends

File ~\AppData\Roaming\Python\Python311\site-packages\phoebe\parameters\__init__.py:2
----> 2 from .parameters import *

File ~\AppData\Roaming\Python\Python311\site-packages\phoebe\parameters\parameters.py:33
     31 from fnmatch import fnmatch
     32 from copy import deepcopy as _deepcopy
---> 33 import readline
     34 import numpy as np
     35 from scipy.stats import norm as _norm

File ~\anaconda3\envs\BinaryResearch24\Lib\site-packages\readline.py:34
      8 __all__ = [ 'parse_and_bind',
      9             'get_line_buffer',
     10             'insert_text',
   (...)
     29             'callback_handler_remove',
     30             'callback_read_char',] #Some other objects are added below
     33 # create a Readline object to contain the state
---> 34 rl = Readline()
     36 if rl.disable_readline:
     37     def dummy(completer=""):

File ~\anaconda3\envs\BinaryResearch24\Lib\site-packages\pyreadline\rlmain.py:422, in Readline.__init__(self)
    421 def __init__(self):
--> 422     BaseReadline.__init__(self)
    423     self.console = console.Console()
    424     self.selection_color = self.console.saveattr<<4

File ~\anaconda3\envs\BinaryResearch24\Lib\site-packages\pyreadline\rlmain.py:62, in BaseReadline.__init__(self)
     60 self.editingmodes = [mode(self) for mode in editingmodes]
     61 for mode in self.editingmodes:
---> 62     mode.init_editing_mode(None)
     63 self.mode = self.editingmodes[0]
     65 self.read_inputrc()

File ~\anaconda3\envs\BinaryResearch24\Lib\site-packages\pyreadline\modes\emacs.py:633, in EmacsMode.init_editing_mode(self, e)
    630 self._bind_exit_key('Control-z')
    632 # I often accidentally hold the shift or control while typing space
--> 633 self._bind_key('space',       self.self_insert)
    634 self._bind_key('Shift-space',       self.self_insert)
    635 self._bind_key('Control-space',     self.self_insert)

File ~\anaconda3\envs\BinaryResearch24\Lib\site-packages\pyreadline\modes\basemode.py:162, in BaseMode._bind_key(self, key, func)
    160 def _bind_key(self, key, func):
    161     """setup the mapping from key to call the function."""
--> 162     if not callable(func):
    163         print("Trying to bind non method to keystroke:%s,%s"%(key,func))
    164         raise ReadlineError("Trying to bind non method to keystroke:%s,%s,%s,%s"%(key,func,type(func),type(self._bind_key)))

File ~\anaconda3\envs\BinaryResearch24\Lib\site-packages\pyreadline\py3k_compat.py:8, in callable(x)
      7 def callable(x):
----> 8     return isinstance(x, collections.Callable)

AttributeError: module 'collections' has no attribute 'Callable'

**Comment by kecnry** [comment]
Can you try updating your installation of readline?  `pip install -U readline` and then restarting the notebook kernel to see if that fixes the issue?

**Comment by DAyres31** [comment]
Thank you for the quick reply! In running the line you gave, I got the following error. I am working on a windows device.

Collecting readline
  Using cached readline-6.2.4.1.tar.gz (2.3 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [1 lines of output]
  error: this module is not meant to work on Windows
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kecnry** [comment]
According to [this](https://stackoverflow.com/questions/51157443/pythons-readline-module-not-available-for-windows), can you try installing pyreadline instead?
